config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/login' , to:'sessions#new'
  post '/login' , to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get '/signup',to:'users#new'
  root to: "static_pages#home"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
          <div class=container>
          <%= link_to "Myrails app",root_path,id: "logo"%>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path%></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Help", static_pages_help_path %></li>

          <% if logged_in? %>
            <li><%= link_to "Users", users_path%></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%=current_user.name.upcase%>
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Update", edit_user_path(current_user) %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Log out", logout_path, method: :delete %></li>
                  </ul>
            </li>

          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
        </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrailsapp</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    a:hover{
      color:white;
      text-decoration: none;
    }
    </Style>
  </head>

  <body>
  <%=render 'layouts/header'%>
  <div class=container>
    <% if !flash[:success].nil? %><div class="alert alert-success"><%=flash[:success]%></div><%end%>
    <% if !flash[:danger].nil? %><div class="alert alert-danger"><%=flash[:danger]%></div><%end%>
    <%= yield %>
  </div>
  </body>
</html>